### ISSUE TITLE
Using with switches?

### ISSUE THREAD

**Issue by ferbulous** [tomrusteze/esphome-esp-now#1]
Hi, is there example for setting this up with switch & light bulbs?

I already have the switch setup in detached mode (if homeassistant goes offline it would toggle the relays) with multiple press setup based on [this](https://www.esphome-devices.com/devices/Shelly-1)

How would i forward those button actions to the esphome bulbs? (i.e single press to toggle lights, long press for dimming)

**Comment by tomrusteze** [comment]
Take a look at the new [examples](https://github.com/tomrusteze/esphome-esp-now/tree/main/examples). Your issue may be resolved, however I do not fully understand your use case.

**Comment by ferbulous** [comment]
Thanks @tomrusteze 
Sorry if i wasn’t being clear on my request
I have switches that are using detached mode for my lights that send the button logs for custom action with lights.

Then in homeassistant, i setup automation based on the button clicks (single click for toggle lights, double click for changing color temperature and long click for dimming). I’d like to move this automation in esphome so it doesn’t rely on homeassistant if it goes offline



```
- platform: gpio
    pin:
      number: GPIO13
      inverted: True
    id: button
    name: ${friendly_name} Button
    on_multi_click:
   # Single Click:
    - timing:
      - ON for at most 1s
      - OFF for at least 0.3s
      then:
        - switch.toggle: ${device_name}
        - logger.log: "Single Click"
        - homeassistant.event:
            event: esphome.${device_name}
            data:
              title: single_click
   # Double Click:
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log: "Double Clicked"
        - homeassistant.event:
            event: esphome.${device_name}
            data:
              title: double_click
    # Long Press:
    - timing:
      - ON for 1s to 2s
      - OFF for at least 0.3s
      then:
        - logger.log: "Single Long Press"
        - homeassistant.event:
            event: esphome.${device_name}
            data:
              title: long_press
    - timing:
      - ON for at least 2.2s
      then:
        - logger.log: "Press and Hold"
        - homeassistant.event:
            event: esphome.${device_name}
            data:
              title: hold
    internal: True
```

**Comment by tomrusteze** [comment]
Okay, some issues at the moment that may hurt your experience.
1. This integration does not support (RGB)CCT lights currently. (I believe you have those)
2. If you change the state of your light through HomeAssistant, your switch will not know this. So using the switch may result in strange behaviour if these states are not synced.
3. In the current state, the switch can control the light, but it has no way of knowing if the light has received this command. In practice this is not a big issue if these devices are in close proximity.

To move your automations to esphome, you could do the following:
1. Setup a light and switch with connection like example 2.
2. Use the light actions from esphome to control the light. See the esphome [docs](https://esphome.io/components/light/index.html#light-toggle-action). Toggling your light would be `light.toggle: light_1`. Dimming and changing colour is also possible using the [light.turn_on](https://esphome.io/components/light/index.html#light-turn-on-action) action.

Please keep in mind that this is highly experimental software. Use it with caution and preferably use a development board to test your setup first.

**Comment by ferbulous** [comment]
> 1\. This integration does not support (RGB)CCT lights currently. (I believe you have those)
> 2\. If you change the state of your light through HomeAssistant, your switch will not know this. So using the switch may result in strange behaviour if these states are not synced.

Meaning for this 2 use:
1) change the color temp/colors/ toggle thru homeassistant app
2) change the color temp/colors/ toggle using the wall switch buttons
If I made changes with (2), then it might not sync with homeassistant?

> 3\. In the current state, the switch can control the light, but it has no way of knowing if the light has received this command. In practice this is not a big issue if these devices are in close proximity.

i intend to test this out with 3 lights in close proximity with the switch (hub)
So I’d need to create 3 light entities in the switch config. Then those lights would be listed in the switch device since it’s the only one connected directly to homeassistant

**Comment by tomrusteze** [comment]
If that is the case, where you only connect your switch to HomeAssistant and the lights to wifi but not to HomeAssistant. Then all communication from HomeAssistant to the light will go through the switch (hub). Thus you should not have the problems discribed in 2. 

> So I’d need to create 3 light entities in the switch config. Then those lights would be listed in the switch device since it’s the only one connected directly to homeassistant

You will indeed need light entities in the switch that are published to HomeAssistant.

**Comment by ferbulous** [comment]
hi, I'm getting this odd errors just compiling for switch.yml

[logs_switch-espnow-test_compile.txt](https://github.com/tomrusteze/esphome-esp-now/files/10511045/logs_switch-espnow-test_compile.txt)


as for light.yml, esphome insist i add username/password for the wifi 

using the default 2-switch & 2-light yaml example 

```
INFO Reading configuration /config/esphome/light-espnow-test.yaml...
WARNING 'light_1': Using the '_' (underscore) character in the hostname is discouraged as it can cause problems with some DHCP and local name services. For more information, see https://esphome.io/guides/faq.html#why-shouldn-t-i-use-underscores-in-my-device-name
Failed config

wifi: [source /config/esphome/light-espnow-test.yaml:12]
  
  Please specify at least an SSID or an Access Point to create.
  networks: []
  reboot_timeout: 300s
  domain: .local
  power_save_mode: NONE
  fast_connect: False
  output_power: 20.0
  use_address: light_1.local
```

**Comment by tomrusteze** [comment]
If you want your lights to be connected to the Wi-Fi to allow for OTA firmware updates, then you should use this example and fill in the wifi credentials. If you do not want that then you should look at example 1 instead of example 2.

**Comment by ferbulous** [comment]
Thanks, got the switch compiled now
But I'm still having errors with the lights

Replaced the neopixel light components with this

```
output:
  - platform: esp8266_pwm
    id: red_output
    pin: GPIO4
  - platform: esp8266_pwm
    id: green_output
    pin: GPIO12
  - platform: esp8266_pwm
    id: blue_output
    pin: GPIO14
  - platform: esp8266_pwm
    id: warm_white_output
    pin: GPIO13
  - platform: esp8266_pwm
    id: white_output
    pin: GPIO5


light:
  - platform: rgbww
    id: light_1
    red: red_output
    green: green_output
    blue: blue_output
    warm_white: warm_white_output
    cold_white: white_output
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 3000 K
    color_interlock: true
```

```
Compiling /data/light/.pioenvs/light/lib67b/ESP8266WiFi/BearSSLHelpers.cpp.o
/config/esphome/light-1.yaml: In lambda function:
/config/esphome/light-1.yaml:70:39: error: invalid conversion from 'esphome::light::LightState*' to 'esphome::light::AddressableLightState*' [-fpermissive]
   70 |       AddressableLightState* dest = id(light_1);
      |                                       ^~~~~~~
      |                                       |
      |                                       esphome::light::LightState*
*** [/data/light/.pioenvs/light/src/main.cpp.o] Error 1
Compiling /data/light/.pioenvs/light/lib67b/ESP8266WiFi/CertStoreBearSSL.cpp.o
========================= [FAILED] Took 62.37 seconds =========================
```
